MyAppT/Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace MyAppT.Models
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
        }
        public DbSet<Register> Register { get; set; }
    }
}

MyAppT/Models/ErrorViewModel.cs
namespace MyAppT.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyAppT/Models/Operations.cs
using Microsoft.EntityFrameworkCore;

namespace MyAppT.Models
{
    public interface IRegisterRepository
    {
        Task<Register> GetByIdAsync(int id);
        Task<List<Register>> ListAsync();
        Task CreateAsync(Register register);
        Task UpdateAsync(Register register);
        Task DeleteAsync(int id);
    }

    public class RegisterRepository : IRegisterRepository
    {
        private readonly AppDbContext context;

        public RegisterRepository(AppDbContext dbContext)
        {
            context = dbContext;
        }

        public Task<Register> GetByIdAsync(int id)
        {
            return context.Register.FirstOrDefaultAsync(s => s.Id == id);
        }

        public Task<List<Register>> ListAsync()
        {
            return context.Register.ToListAsync();
        }

        public Task CreateAsync(Register register)
        {
            context.Register.Add(register);
            return context.SaveChangesAsync();
        }

        public Task UpdateAsync(Register register)
        {
            context.Entry(register).State = EntityState.Modified;
            return context.SaveChangesAsync();
        }
        public async Task DeleteAsync(int id)
        {
            var r = await GetByIdAsync(id);
            context.Remove(r);
            await context.SaveChangesAsync();
        }
    }
}

MyAppT/Models/Register.cs
using System.ComponentModel.DataAnnotations;

namespace MyAppT.Models
{
    public class Register
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Range(40, 60)]
        public int Age { get; set; }
    }
}

MyAppT/Models/Reservation.cs
namespace MyAppT.Models
{
    public class Reservation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string StartLocation { get; set; }
        public string EndLocation { get; set; }
    }
}

MyAppT/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyAppT.Models;
using System.Diagnostics;

namespace MyAppT.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyAppT/Controllers/PartyController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyAppT.Controllers
{
    public class PartyController : Controller
    {
        public IActionResult Entry()
        {
            return View();
        }
 
        [HttpPost]
        public IActionResult Entry(string name, string membership)
        {
            if (string.IsNullOrEmpty(name))
                ModelState.AddModelError("name", "Please enter your name");
            if (string.IsNullOrEmpty(membership))
                ModelState.AddModelError("membership", "Please enter your membership");
 
            if (ModelState.IsValid)
            {
                string nm = name + "," + membership;
                return View((object)nm);
            }
            else
                return BadRequest(ModelState);
        }
    }
}

MyAppT/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using MyAppT.Models;

namespace MyAppT.Controllers
{
    public class RegisterController : Controller
    {
        private IRegisterRepository context;
        public RegisterController(IRegisterRepository appDbContext)
        {
            context = appDbContext;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Register register)
        {
            if (ModelState.IsValid)
            {
                await context.CreateAsync(register);
                return RedirectToAction("Read");
            }
            else
                return View();
        }

        public async Task<IActionResult> Read()
        {
            var rl = await context.ListAsync();
            return View(rl);
        }

        public async Task<IActionResult> Update(int id)
        {
            Register r = await context.GetByIdAsync(id);
            return View(r);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Register register)
        {
            if (ModelState.IsValid)
            {
                await context.UpdateAsync(register);
                ViewBag.Result = "Success";
            }
            return View(register);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await context.DeleteAsync(id);
            return RedirectToAction("Read");
        }
    }
}

MyAppT/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyAppT.Infrastructure;
using MyAppT.Models;

namespace MyAppT.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ReservationController : ControllerBase
    {
        private IRepository repository;
        public ReservationController(IRepository repo) => repository = repo;

        [HttpGet]
        public IEnumerable<Reservation> Get() => repository.Reservations;

        [HttpGet("{id}")]
        public ActionResult<Reservation> Get(int id)
        {
            if (id == 0)
                return BadRequest("Value must be passed in the request body.");

            Reservation r = repository[id];

            if (r is null)
                return NotFound();

            return Ok(r);
        }

        [HttpPost]
        public Reservation Post([FromBody] Reservation res) =>
            repository.AddReservation(new Reservation
              {
                  Name = res.Name,
                  StartLocation = res.StartLocation,
                  EndLocation = res.EndLocation
              });

        [HttpPut]
        public Reservation Put([FromBody] Reservation res) =>
                   repository.UpdateReservation(res);

        [HttpDelete("{id}")]
        public void Delete(int id) => repository.DeleteReservation(id);

    }
}

MyAppT/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p class="h3">See the <a href="https://www.hosting.work/aspnet-core-xunit-unit-testing/" target="_blank">xUnit Tutorial here</a>.</p>
    <div class="bg-warning">
        <p>Check the Blow Links:</p>
        <p><a asp-controller="Party" asp-action="Entry">Party Entry</a></p>
    </div>
    <p class="h3">See the <a href="https://www.hosting.work/aspnet-core-moq-xunit-unit-testing/" target="_blank">Moq and xUnit for Unit Testing Controllers</a>.</p>
    <div class="bg-warning">
        <p>Check the Blow Links:</p>
        <p><a asp-controller="Register" asp-action="Read">CRUD</a></p>
    </div>
</div>

MyAppT/Views/Party/Entry.cshtml
@model string

@{
    ViewData["Title"] = "Add Party Entry";
}

<h1 class="bg-info text-white">Add Party Entry</h1>
<div asp-validation-summary="All" class="text-danger btn-light"></div>

<form class="m-1 p-1" method="post">
    <div class="form-group">
        <label>Name</label>
        <input name="Name" type="text" class="form-control" />
    </div>
    <div class="form-group">
        <label>Membership</label>
        <input name="Membership" type="text" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@{
    if (Model != null)
    {
        <h2 class="bg-danger text-white">Welcome to the Party</h2>
        <h2 class="bg-info text-white">Tomorrow at 9:00 PM</h2>
        <table class="table table-sm table-bordered">
            <tr>
                <th>Name</th>
                <th>Membership</th>
            </tr>

            <tr>
                <td>@Model.ToString().Split(',')[0]</td>
                <td>@Model.ToString().Split(',')[1]</td>
            </tr>
        </table>
    }
}

MyAppT/Views/Register/Create.cshtml
@model Register

@{
    ViewData["Title"] = "Create Record";
}

<h1 class="bg-info text-white">Create Record</h1>
<a asp-action="Read" class="btn btn-secondary">View all</a>

<div asp-validation-summary="All" class="text-danger btn-light"></div>

<form method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input type="text" asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Age"></label>
        <input type="text" asp-for="Age" class="form-control" />
        <span asp-validation-for="Age" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

MyAppT/Views/Register/Read.cshtml
@model List<Register>

@{
    ViewData["Title"] = "Records";
}

<h1 class="bg-info text-white">Records</h1>
<a asp-action="Create" class="btn btn-secondary">Create</a>

<table class="table table-sm table-bordered">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Age</th>
        <th></th>
        <th></th>
    </tr>
    @foreach (Register r in Model)
    {
        <tr>
            <td>@r.Id</td>
            <td>@r.Name</td>
            <td>@r.Age</td>
            <td>
                <a class="btn btn-sm btn-primary" asp-action="Update" asp-route-id="@r.Id">Update</a>
            </td>
            <td>
                <form asp-action="Delete" asp-route-id="@r.Id" method="post">
                    <button type="submit" class="btn btn-sm btn-danger">
                        Delete
                    </button>
                </form>
            </td>
        </tr>
    }
</table>

MyAppT/Views/Register/Update.cshtml
@model Register

@{
    ViewData["Title"] = "Update Record";
}

<h1 class="bg-info text-white">Update Record</h1>
<a asp-action="Read" class="btn btn-secondary">View all</a>
<h2 class="bg-light">@ViewBag.Result</h2>

<div asp-validation-summary="All" class="text-danger btn-light"></div>

<form method="post">
    <div class="form-group">
        <label asp-for="Id"></label>
        <input type="text" asp-for="Id" disabled class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input type="text" asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Age"></label>
        <input type="text" asp-for="Age" class="form-control" />
        <span asp-validation-for="Age" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Update</button>
</form>

MyAppT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyAppT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyAppT.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyAppT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Party" asp-action="Entry">Party Entry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Read">CRUD</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MyAppT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>